package mcpserver

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/soggycactus/paprika-3-mcp/internal/aisles"
	"github.com/soggycactus/paprika-3-mcp/internal/paprika"
)

type Options struct {
	Version            string
	Username           string
	Password           string
	RefreshInterval    time.Duration
	AisleMapPath       string
	DefaultGroceryList string
	Logger             *slog.Logger
}


func NewServer(opts Options) (*Server, error) {
	paprika3, err := paprika.NewClient(opts.Username, opts.Password, opts.Version, opts.Logger)
	if err != nil {
		return nil, err
	}

	refreshInterval := opts.RefreshInterval
	if refreshInterval == 0 {
		refreshInterval = 5 * time.Minute
	}

	am, err := aisles.Load(opts.AisleMapPath)
	if err != nil {
		return nil, fmt.Errorf("loading aisle map from %s: %w", opts.AisleMapPath, err)
	}

	s := server.NewMCPServer("paprika-3-mcp", opts.Version, server.WithResourceCapabilities(false, false))
	return &Server{
		paprika3:           paprika3,
		server:             s,
		logger:             opts.Logger,
		refreshInterval:    refreshInterval,
		aisleMap:           am,
		aisleMapPath:       opts.AisleMapPath,
		defaultGroceryList: opts.DefaultGroceryList,
		recipes:            make(map[string]*paprika.Recipe),
	}, nil
}

type Server struct {
	paprika3           *paprika.Client
	logger             *slog.Logger
	server             *server.MCPServer
	refreshInterval    time.Duration
	aisleMap           aisles.AisleMap
	aisleMapPath       string
	defaultGroceryList string
	recipes            map[string]*paprika.Recipe
	recipesMu          sync.RWMutex
}

func (s *Server) Start() {
	s.addResources() // load synchronously so resources are ready when the client connects
	go func() {
		ticker := time.NewTicker(s.refreshInterval)
		for range ticker.C {
			s.addResources()
		}
	}()

	createRecipeTool := mcp.NewTool("create_paprika_recipe",
		mcp.WithDescription("Save new recipes generated by LLMs in the Paprika 3 app"),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.DefaultString("")),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.DefaultString("")),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.DefaultString("")),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.DefaultString("")),
		mcp.WithArray("categories",
			mcp.Description("List of category names to assign (e.g. [\"Holy Quad\", \"Protein: Chicken\", \"Cuisine: Mexican\"])"),
		),
		mcp.WithNumber("rating",
			mcp.Description("Star rating 0-5 (0 = unrated)"),
		),
	)
	updateRecipeTool := mcp.NewTool("update_paprika_recipe",
		mcp.WithDescription("Update existing recipes in the Paprika 3 app"),
		mcp.WithString("uid", mcp.Description("The UID of the recipe"), mcp.Required()),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.Required()),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.Required()),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.Required()),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.Required()),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.Required()),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.Required()),
		mcp.WithArray("categories",
			mcp.Description("List of category names to assign (e.g. [\"Holy Quad\", \"Protein: Chicken\", \"Cuisine: Mexican\"])"),
		),
		mcp.WithNumber("rating",
			mcp.Description("Star rating 0-5 (0 = unrated)"),
		),
	)
	s.server.AddTools(server.ServerTool{
		Tool:    createRecipeTool,
		Handler: s.createRecipe,
	}, server.ServerTool{
		Tool:    updateRecipeTool,
		Handler: s.updateRecipe,
	},
		server.ServerTool{Tool: getGroceryListTool(), Handler: s.getGroceryList},
		server.ServerTool{Tool: updateGroceryItemAisleTool(), Handler: s.updateGroceryItemAisle},
		server.ServerTool{Tool: setupWoodmansAislesTool(), Handler: s.setupWoodmansAisles},
		server.ServerTool{Tool: getMealPlanTool(), Handler: s.getMealPlan},
		server.ServerTool{Tool: addMealToPlanTool(), Handler: s.addMealToPlan},
		server.ServerTool{Tool: listRecipesTool(), Handler: s.listRecipes},
		server.ServerTool{Tool: getRecipeTool(), Handler: s.getRecipe},
		server.ServerTool{Tool: getPantryTool(), Handler: s.getPantry},
	)

	if err := server.ServeStdio(s.server); err != nil {
		s.logger.Error("Server error", "err", err)
	}
}

func (s *Server) addResources() {
	s.logger.Info("Updating recipe resources")
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	// List all recipes to expose them as resources
	recipes, err := s.paprika3.ListRecipes(ctx)
	if err != nil {
		s.logger.Error("failed to list paprika recipes", "err", err)
		return
	}

	if len(recipes.Result) >= 10 {
		s.logger.Info("adding recipes resources concurrently")
		s.addResourcesConcurrently(recipes)
		return
	}

	for _, r := range recipes.Result {
		if err := s.addRecipeResource(r.UID); err != nil {
			s.logger.Error("failed to add recipe as MCP resource", "err", err)
		}
	}
}

func (s *Server) addRecipeResource(uid string) error {
	start := time.Now()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.GetRecipe(ctx, uid)
	if err != nil {
		return err
	}

	if recipe.InTrash {
		return nil
	}

	s.recipesMu.Lock()
	s.recipes[recipe.UID] = recipe
	s.recipesMu.Unlock()

	resourceContents := mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}

	s.server.AddResource(mcp.NewResource(fmt.Sprintf("paprika://recipes/%s", recipe.UID), recipe.Name, mcp.WithResourceDescription(recipe.ResourceDescription()), mcp.WithMIMEType("text/markdown")), func(ctx context.Context, request mcp.ReadResourceRequest) ([]mcp.ResourceContents, error) {
		return []mcp.ResourceContents{resourceContents}, nil
	})

	duration := time.Since(start)
	s.logger.Info("Added resource", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return nil
}

func (s *Server) addResourcesConcurrently(recipes *paprika.RecipeList) {
	buffer := make(chan struct{}, 10)

	for _, r := range recipes.Result {
		go func() (err error) {
			buffer <- struct{}{}
			defer func() {
				<-buffer
			}()

			defer func(err error) {
				if err != nil {
					s.logger.Error("failed to add recipe as MCP resource", "err", err)
				}
			}(err)

			return s.addRecipeResource(r.UID)
		}()
	}
}

func (s *Server) createRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	name, ok := req.Params.Arguments["name"].(string)
	if !ok || len(name) == 0 {
		return nil, errors.New("name is required")
	}
	ingredients, ok := req.Params.Arguments["ingredients"].(string)
	if !ok || len(ingredients) == 0 {
		return nil, errors.New("ingredients are required")
	}
	directions, ok := req.Params.Arguments["directions"].(string)
	if !ok || len(directions) == 0 {
		return nil, errors.New("directions are required")
	}
	servings, _ := req.Params.Arguments["servings"].(string)
	prepTime, _ := req.Params.Arguments["prep_time"].(string)
	cookTime, _ := req.Params.Arguments["cook_time"].(string)
	description, _ := req.Params.Arguments["description"].(string)
	notes, _ := req.Params.Arguments["notes"].(string)
	difficulty, _ := req.Params.Arguments["difficulty"].(string)

	categories, _ := req.Params.Arguments["categories"].([]interface{})
	rating, _ := req.Params.Arguments["rating"].(float64)

	cats := make([]string, len(categories))
	for i, c := range categories {
		cats[i], _ = c.(string)
	}

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.SaveRecipe(ctx, paprika.Recipe{
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
		Categories:  cats,
		Rating:      int(rating),
	})
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Created recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}

func getGroceryListTool() mcp.Tool {
	return mcp.NewTool("get_grocery_list",
		mcp.WithDescription("Fetch all items in a Paprika grocery list with their current aisle assignments."),
		mcp.WithString("list_name",
			mcp.Description("Name of the grocery list (not yet implemented — all items are returned regardless of this value)."),
		),
	)
}

func (s *Server) getGroceryList(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	items, err := s.paprika3.ListGroceryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var sb strings.Builder
	sb.WriteString("## Grocery List\n\n")
	sb.WriteString("| Item | Aisle | Checked |\n|---|---|---|\n")
	for _, item := range items {
		name := item.Name
		if name == "" {
			name = item.Ingredient
		}
		checked := " "
		if item.Checked {
			checked = "x"
		}
		sb.WriteString(fmt.Sprintf("| %s | %s | [%s] |\n", name, item.Aisle, checked))
	}

	return mcp.NewToolResultText(sb.String()), nil
}

func updateGroceryItemAisleTool() mcp.Tool {
	return mcp.NewTool("update_grocery_item_aisle",
		mcp.WithDescription("Set the aisle label on one or more grocery items. Pass an array of {uid, aisle} objects."),
		mcp.WithArray("items",
			mcp.Description("Array of objects with 'uid' (string) and 'aisle' (string) fields."),
			mcp.Required(),
		),
	)
}

func (s *Server) updateGroceryItemAisle(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	rawItems, ok := req.Params.Arguments["items"].([]interface{})
	if !ok {
		return mcp.NewToolResultError("items must be an array"), nil
	}

	existing, err := s.paprika3.ListGroceryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	byUID := make(map[string]paprika.GroceryItem, len(existing))
	for _, item := range existing {
		byUID[item.UID] = item
	}

	var updated, errs []string
	for _, raw := range rawItems {
		m, _ := raw.(map[string]interface{})
		uid, _ := m["uid"].(string)
		aisle, _ := m["aisle"].(string)
		if uid == "" || aisle == "" {
			errs = append(errs, fmt.Sprintf("skipped entry missing uid or aisle: %v", m))
			continue
		}
		item, exists := byUID[uid]
		if !exists {
			errs = append(errs, fmt.Sprintf("uid not found: %s", uid))
			continue
		}
		item.Aisle = aisle
		if err := s.paprika3.UpdateGroceryItem(ctx, item); err != nil {
			errs = append(errs, fmt.Sprintf("failed to update %s: %v", uid, err))
			continue
		}
		updated = append(updated, item.Ingredient)
	}

	msg := fmt.Sprintf("Updated %d items.", len(updated))
	if len(errs) > 0 {
		msg += "\nErrors:\n- " + strings.Join(errs, "\n- ")
	}
	return mcp.NewToolResultText(msg), nil
}

func setupWoodmansAislesTool() mcp.Tool {
	return mcp.NewTool("setup_woodmans_aisles",
		mcp.WithDescription("Map all grocery list items to their Woodman's East aisle. dry_run=true (default) shows proposed changes without writing. Set dry_run=false to commit. Items not found in the aisle map are flagged for manual review."),
		mcp.WithBoolean("dry_run",
			mcp.Description("If true (default), return proposed changes without writing to Paprika."),
		),
	)
}

func (s *Server) setupWoodmansAisles(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	dryRun := true
	if v, ok := req.Params.Arguments["dry_run"].(bool); ok {
		dryRun = v
	}

	items, err := s.paprika3.ListGroceryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	type proposal struct {
		item     paprika.GroceryItem
		newAisle string
	}

	var proposals []proposal
	var unknown []string

	for _, item := range items {
		lookupKey := item.Name
		if lookupKey == "" {
			lookupKey = item.Ingredient
		}
		aisle, found := s.aisleMap.Lookup(lookupKey)
		if !found {
			unknown = append(unknown, lookupKey)
			continue
		}
		if aisle != item.Aisle {
			proposals = append(proposals, proposal{item: item, newAisle: aisle})
		}
	}

	var sb strings.Builder
	mode := "DRY RUN — no changes written"
	if !dryRun {
		mode = "APPLYING CHANGES"
	}
	sb.WriteString(fmt.Sprintf("## setup_woodmans_aisles (%s)\n\n", mode))

	if len(proposals) > 0 {
		sb.WriteString("### Changes\n\n| Item | Current Aisle | → New Aisle |\n|---|---|---|\n")
		var applyErrs []string
		for _, p := range proposals {
			displayName := p.item.Name
			if displayName == "" {
				displayName = p.item.Ingredient
			}
			sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", displayName, p.item.Aisle, p.newAisle))
			if !dryRun {
				p.item.Aisle = p.newAisle
				if err := s.paprika3.UpdateGroceryItem(ctx, p.item); err != nil {
					applyErrs = append(applyErrs, fmt.Sprintf("%s: %v", displayName, err))
				}
			}
		}
		if len(applyErrs) > 0 {
			sb.WriteString("\n### Errors\n\n")
			for _, e := range applyErrs {
				sb.WriteString(fmt.Sprintf("- ⚠️ %s\n", e))
			}
		}
	} else {
		sb.WriteString("All items already have correct aisle assignments.\n")
	}

	if len(unknown) > 0 {
		sb.WriteString("\n### Unknown items (not in aisle map — review and add manually)\n\n")
		for _, u := range unknown {
			sb.WriteString(fmt.Sprintf("- %s\n", u))
		}
		sb.WriteString("\nTo add them: update `aisles/woodmans_east.json` and re-run.\n")
	}

	return mcp.NewToolResultText(sb.String()), nil
}

func (s *Server) updateRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	uid, ok := req.Params.Arguments["uid"].(string)
	if !ok || len(uid) == 0 {
		return nil, errors.New("uid is required")
	}
	name, ok := req.Params.Arguments["name"].(string)
	if !ok || len(name) == 0 {
		return nil, errors.New("name is required")
	}
	ingredients, ok := req.Params.Arguments["ingredients"].(string)
	if !ok || len(ingredients) == 0 {
		return nil, errors.New("ingredients are required")
	}
	directions, ok := req.Params.Arguments["directions"].(string)
	if !ok || len(directions) == 0 {
		return nil, errors.New("directions are required")
	}
	description, ok := req.Params.Arguments["description"].(string)
	if !ok {
		return nil, errors.New("description is required")
	}
	servings, ok := req.Params.Arguments["servings"].(string)
	if !ok {
		return nil, errors.New("servings is required")
	}
	prepTime, ok := req.Params.Arguments["prep_time"].(string)
	if !ok {
		return nil, errors.New("prepTime is required")
	}
	cookTime, ok := req.Params.Arguments["cook_time"].(string)
	if !ok {
		return nil, errors.New("cookTime is required")
	}
	notes, ok := req.Params.Arguments["notes"].(string)
	if !ok {
		return nil, errors.New("notes is required")
	}
	difficulty, ok := req.Params.Arguments["difficulty"].(string)
	if !ok {
		return nil, errors.New("difficulty is required")
	}

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	recipe := paprika.Recipe{
		UID:         uid,
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
	}

	if rawCats, ok := req.Params.Arguments["categories"]; ok && rawCats != nil {
		categories, _ := rawCats.([]interface{})
		cats := make([]string, len(categories))
		for i, c := range categories {
			cats[i], _ = c.(string)
		}
		recipe.Categories = cats
	}

	if rawRating, ok := req.Params.Arguments["rating"]; ok && rawRating != nil {
		rating, _ := rawRating.(float64)
		recipe.Rating = int(rating)
	}

	savedRecipe, err := s.paprika3.SaveRecipe(ctx, recipe)
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Updated recipe", "name", savedRecipe.Name, "uid", savedRecipe.UID, "duration", duration)

	return mcp.NewToolResultResource(savedRecipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", savedRecipe.UID),
		MIMEType: "text/markdown",
		Text:     savedRecipe.ToMarkdown(),
	}), nil
}

func getMealPlanTool() mcp.Tool {
	return mcp.NewTool("get_meal_plan",
		mcp.WithDescription("Fetch the meal plan for a date range."),
		mcp.WithString("start_date",
			mcp.Description("Start date in YYYY-MM-DD format."),
			mcp.Required(),
		),
		mcp.WithString("end_date",
			mcp.Description("End date in YYYY-MM-DD format."),
			mcp.Required(),
		),
	)
}

func (s *Server) getMealPlan(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	startStr, _ := req.Params.Arguments["start_date"].(string)
	endStr, _ := req.Params.Arguments["end_date"].(string)

	start, err := time.Parse("2006-01-02", startStr)
	if err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("invalid start_date: %v", err)), nil
	}
	end, err := time.Parse("2006-01-02", endStr)
	if err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("invalid end_date: %v", err)), nil
	}
	if end.Before(start) {
		return mcp.NewToolResultError("end_date must not be before start_date"), nil
	}

	entries, err := s.paprika3.ListMealPlanEntries(ctx, start, end)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	mealTypeName := map[int]string{0: "Breakfast", 1: "Lunch", 2: "Dinner", 3: "Snack"}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("## Meal Plan: %s to %s\n\n", startStr, endStr))
	if len(entries) == 0 {
		sb.WriteString("No meals planned for this period.\n")
	} else {
		sb.WriteString("| Date | Meal | Recipe |\n|---|---|---|\n")
		for _, e := range entries {
			sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", e.Date, mealTypeName[e.MealType], e.RecipeName))
		}
	}

	return mcp.NewToolResultText(sb.String()), nil
}

func addMealToPlanTool() mcp.Tool {
	return mcp.NewTool("add_meal_to_plan",
		mcp.WithDescription("Add a recipe to the meal plan. Idempotent — if the same recipe is already in this slot on this date, does nothing."),
		mcp.WithString("recipe_uid",
			mcp.Description("UID of the recipe to add."),
			mcp.Required(),
		),
		mcp.WithString("date",
			mcp.Description("Date in YYYY-MM-DD format."),
			mcp.Required(),
		),
		mcp.WithString("meal_type",
			mcp.Description("One of: breakfast, lunch, dinner, snack"),
			mcp.Required(),
		),
	)
}

func (s *Server) addMealToPlan(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	recipeUID, _ := req.Params.Arguments["recipe_uid"].(string)
	if recipeUID == "" {
		return mcp.NewToolResultError("recipe_uid is required"), nil
	}
	dateStr, _ := req.Params.Arguments["date"].(string)
	mealTypeStr, _ := req.Params.Arguments["meal_type"].(string)

	mealTypeMap := map[string]int{
		"breakfast": paprika.MealTypeBreakfast,
		"lunch":     paprika.MealTypeLunch,
		"dinner":    paprika.MealTypeDinner,
		"snack":     paprika.MealTypeSnack,
	}
	mealType, ok := mealTypeMap[strings.ToLower(mealTypeStr)]
	if !ok {
		return mcp.NewToolResultError("meal_type must be one of: breakfast, lunch, dinner, snack"), nil
	}

	date, err := time.Parse("2006-01-02", dateStr)
	if err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("invalid date: %v", err)), nil
	}

	// Idempotency check.
	// time.Parse("2006-01-02", ...) returns UTC midnight. ListMealPlanEntries
	// filters using Truncate(24h) comparisons, also in UTC. This is correct
	// as long as the server is not running in a non-UTC timezone that shifts
	// the date boundary — keep TZ=UTC in the MCP config env to be safe.
	existing, err := s.paprika3.ListMealPlanEntries(ctx, date, date)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	for _, e := range existing {
		if e.RecipeUID == recipeUID && e.MealType == mealType {
			return mcp.NewToolResultText(fmt.Sprintf(
				"Recipe already in %s slot on %s — no change made.", mealTypeStr, dateStr,
			)), nil
		}
	}

	entry := paprika.MealPlanEntry{
		RecipeUID:  recipeUID,
		RecipeName: recipeUID, // fallback: use UID as name; Paprika will resolve the display name
		Date:       dateStr,
		MealType:   mealType,
	}

	if err := s.paprika3.SaveMealPlanEntry(ctx, entry); err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	return mcp.NewToolResultText(fmt.Sprintf(
		"Added recipe to %s on %s.", mealTypeStr, dateStr,
	)), nil
}

func listRecipesTool() mcp.Tool {
	return mcp.NewTool("list_recipes",
		mcp.WithDescription("List all recipes with name, UID, categories, prep/cook time, and star rating. Use get_recipe to fetch full ingredients and directions for a specific recipe."),
	)
}

func (s *Server) listRecipes(_ context.Context, _ mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	s.recipesMu.RLock()
	recipes := make([]*paprika.Recipe, 0, len(s.recipes))
	for _, r := range s.recipes {
		recipes = append(recipes, r)
	}
	s.recipesMu.RUnlock()

	if len(recipes) == 0 {
		return mcp.NewToolResultText("No recipes found. Resources may still be loading — try again in a moment."), nil
	}

	sort.Slice(recipes, func(i, j int) bool {
		return recipes[i].Name < recipes[j].Name
	})

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("## Recipes (%d total)\n\n", len(recipes)))
	sb.WriteString("| Name | UID | Categories | Prep | Cook | Rating |\n|---|---|---|---|---|---|\n")
	for _, r := range recipes {
		cats := strings.Join(r.Categories, ", ")
		sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %d |\n",
			r.Name, r.UID, cats, r.PrepTime, r.CookTime, r.Rating))
	}
	return mcp.NewToolResultText(sb.String()), nil
}

func getRecipeTool() mcp.Tool {
	return mcp.NewTool("get_recipe",
		mcp.WithDescription("Fetch full recipe content (ingredients, directions, notes) by UID."),
		mcp.WithString("uid", mcp.Description("The UID of the recipe."), mcp.Required()),
	)
}

func (s *Server) getRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	uid, _ := req.Params.Arguments["uid"].(string)
	if uid == "" {
		return mcp.NewToolResultError("uid is required"), nil
	}

	s.recipesMu.RLock()
	recipe, ok := s.recipes[uid]
	s.recipesMu.RUnlock()

	if !ok {
		ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
		defer cancel()
		var err error
		recipe, err = s.paprika3.GetRecipe(ctx, uid)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
	}

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}

func getPantryTool() mcp.Tool {
	return mcp.NewTool("get_pantry",
		mcp.WithDescription("Fetch all items in the Paprika pantry with name, quantity, and in-stock status."),
	)
}

func (s *Server) getPantry(ctx context.Context, _ mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	items, err := s.paprika3.ListPantryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	if len(items) == 0 {
		return mcp.NewToolResultText("Pantry is empty."), nil
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("## Pantry (%d items)\n\n", len(items)))
	sb.WriteString("| Item | Quantity | In Stock |\n|---|---|---|\n")
	for _, item := range items {
		name := item.Name
		if name == "" {
			name = item.Ingredient
		}
		inStock := "no"
		if item.InStock {
			inStock = "yes"
		}
		sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", name, item.Quantity, inStock))
	}
	return mcp.NewToolResultText(sb.String()), nil
}
