package mcpserver

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/soggycactus/paprika-3-mcp/internal/aisles"
	"github.com/soggycactus/paprika-3-mcp/internal/paprika"
	"github.com/soggycactus/paprika-3-mcp/internal/rules"
)

type Options struct {
	Version              string
	Username             string
	Password             string
	RefreshInterval      time.Duration
	AisleMapPath         string
	HouseholdRulesPath   string
	DefaultGroceryList   string
	Logger               *slog.Logger
}


func NewServer(opts Options) (*Server, error) {
	paprika3, err := paprika.NewClient(opts.Username, opts.Password, opts.Version, opts.Logger)
	if err != nil {
		return nil, err
	}

	refreshInterval := opts.RefreshInterval
	if refreshInterval == 0 {
		refreshInterval = 5 * time.Minute
	}

	am, err := aisles.Load(opts.AisleMapPath)
	if err != nil {
		return nil, fmt.Errorf("loading aisle map from %s: %w", opts.AisleMapPath, err)
	}

	hr, err := rules.Load(opts.HouseholdRulesPath)
	if err != nil {
		return nil, fmt.Errorf("loading household rules from %s: %w", opts.HouseholdRulesPath, err)
	}

	s := server.NewMCPServer("paprika-3-mcp", opts.Version, server.WithResourceCapabilities(false, false))
	return &Server{
		paprika3:             paprika3,
		server:               s,
		logger:               opts.Logger,
		refreshInterval:      refreshInterval,
		aisleMap:             am,
		aisleMapPath:         opts.AisleMapPath,
		householdRules:       hr,
		householdRulesPath:   opts.HouseholdRulesPath,
		defaultGroceryList:   opts.DefaultGroceryList,
		recipes:              make(map[string]*paprika.Recipe),
	}, nil
}

type Server struct {
	paprika3             *paprika.Client
	logger               *slog.Logger
	server               *server.MCPServer
	refreshInterval      time.Duration
	aisleMap             aisles.AisleMap
	aisleMapPath         string
	householdRules       rules.Rules
	householdRulesPath   string
	defaultGroceryList   string
	recipes              map[string]*paprika.Recipe
	recipesMu            sync.RWMutex
	rulesMu              sync.RWMutex
}

func (s *Server) Start() {
	s.addResources() // load synchronously so resources are ready when the client connects
	go func() {
		ticker := time.NewTicker(s.refreshInterval)
		for range ticker.C {
			s.addResources()
		}
	}()

	createRecipeTool := mcp.NewTool("create_paprika_recipe",
		mcp.WithDescription("Save new recipes generated by LLMs in the Paprika 3 app"),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.DefaultString("")),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.DefaultString("")),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.DefaultString("")),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.DefaultString("")),
		mcp.WithArray("categories",
			mcp.Description("List of category names to assign (e.g. [\"Holy Quad\", \"Protein: Chicken\", \"Cuisine: Mexican\"])"),
		),
		mcp.WithNumber("rating",
			mcp.Description("Star rating 0-5 (0 = unrated)"),
		),
	)
	updateRecipeTool := mcp.NewTool("update_paprika_recipe",
		mcp.WithDescription("Update existing recipes in the Paprika 3 app"),
		mcp.WithString("uid", mcp.Description("The UID of the recipe"), mcp.Required()),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.Required()),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.Required()),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.Required()),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.Required()),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.Required()),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.Required()),
		mcp.WithArray("categories",
			mcp.Description("List of category names to assign (e.g. [\"Holy Quad\", \"Protein: Chicken\", \"Cuisine: Mexican\"])"),
		),
		mcp.WithNumber("rating",
			mcp.Description("Star rating 0-5 (0 = unrated)"),
		),
	)
	s.server.AddTools(server.ServerTool{
		Tool:    createRecipeTool,
		Handler: s.createRecipe,
	}, server.ServerTool{
		Tool:    updateRecipeTool,
		Handler: s.updateRecipe,
	},
		server.ServerTool{Tool: getGroceryListTool(), Handler: s.getGroceryList},
		server.ServerTool{Tool: updateGroceryItemAisleTool(), Handler: s.updateGroceryItemAisle},
		server.ServerTool{Tool: setupWoodmansAislesTool(), Handler: s.setupWoodmansAisles},
		server.ServerTool{Tool: getMealPlanTool(), Handler: s.getMealPlan},
		server.ServerTool{Tool: addMealToPlanTool(), Handler: s.addMealToPlan},
		server.ServerTool{Tool: listRecipesTool(), Handler: s.listRecipes},
		server.ServerTool{Tool: getRecipeTool(), Handler: s.getRecipe},
		server.ServerTool{Tool: getPantryTool(), Handler: s.getPantry},
		server.ServerTool{Tool: addPantryItemTool(), Handler: s.addPantryItem},
		server.ServerTool{Tool: updatePantryItemTool(), Handler: s.updatePantryItem},
		server.ServerTool{Tool: deletePantryItemTool(), Handler: s.deletePantryItem},
		server.ServerTool{Tool: setupPantryAislesTool(), Handler: s.setupPantryAisles},
		server.ServerTool{Tool: removeMealFromPlanTool(), Handler: s.removeMealFromPlan},
		server.ServerTool{Tool: addGroceryItemTool(), Handler: s.addGroceryItem},
		server.ServerTool{Tool: uncheckGroceryItemsTool(), Handler: s.uncheckGroceryItems},
		server.ServerTool{Tool: deleteGroceryItemsTool(), Handler: s.deleteGroceryItems},
		server.ServerTool{Tool: syncGroceryListToPantryTool(), Handler: s.syncGroceryListToPantry},
		server.ServerTool{Tool: getHouseholdRulesTool(), Handler: s.getHouseholdRules},
		server.ServerTool{Tool: setHouseholdRuleTool(), Handler: s.setHouseholdRule},
	)

	if err := server.ServeStdio(s.server); err != nil {
		s.logger.Error("Server error", "err", err)
	}
}

func (s *Server) addResources() {
	s.logger.Info("Updating recipe resources")
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	// List all recipes to expose them as resources
	recipes, err := s.paprika3.ListRecipes(ctx)
	if err != nil {
		s.logger.Error("failed to list paprika recipes", "err", err)
		return
	}

	if len(recipes.Result) >= 10 {
		s.logger.Info("adding recipes resources concurrently")
		s.addResourcesConcurrently(recipes)
		return
	}

	for _, r := range recipes.Result {
		if err := s.addRecipeResource(r.UID); err != nil {
			s.logger.Error("failed to add recipe as MCP resource", "err", err)
		}
	}
}

func (s *Server) addRecipeResource(uid string) error {
	start := time.Now()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.GetRecipe(ctx, uid)
	if err != nil {
		return err
	}

	if recipe.InTrash {
		return nil
	}

	s.recipesMu.Lock()
	s.recipes[recipe.UID] = recipe
	s.recipesMu.Unlock()

	resourceContents := mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}

	s.server.AddResource(mcp.NewResource(fmt.Sprintf("paprika://recipes/%s", recipe.UID), recipe.Name, mcp.WithResourceDescription(recipe.ResourceDescription()), mcp.WithMIMEType("text/markdown")), func(ctx context.Context, request mcp.ReadResourceRequest) ([]mcp.ResourceContents, error) {
		return []mcp.ResourceContents{resourceContents}, nil
	})

	duration := time.Since(start)
	s.logger.Info("Added resource", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return nil
}

func (s *Server) addResourcesConcurrently(recipes *paprika.RecipeList) {
	buffer := make(chan struct{}, 10)

	for _, r := range recipes.Result {
		go func() (err error) {
			buffer <- struct{}{}
			defer func() {
				<-buffer
			}()

			defer func(err error) {
				if err != nil {
					s.logger.Error("failed to add recipe as MCP resource", "err", err)
				}
			}(err)

			return s.addRecipeResource(r.UID)
		}()
	}
}

func (s *Server) createRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	name, ok := req.Params.Arguments["name"].(string)
	if !ok || len(name) == 0 {
		return nil, errors.New("name is required")
	}
	ingredients, ok := req.Params.Arguments["ingredients"].(string)
	if !ok || len(ingredients) == 0 {
		return nil, errors.New("ingredients are required")
	}
	directions, ok := req.Params.Arguments["directions"].(string)
	if !ok || len(directions) == 0 {
		return nil, errors.New("directions are required")
	}
	servings, _ := req.Params.Arguments["servings"].(string)
	prepTime, _ := req.Params.Arguments["prep_time"].(string)
	cookTime, _ := req.Params.Arguments["cook_time"].(string)
	description, _ := req.Params.Arguments["description"].(string)
	notes, _ := req.Params.Arguments["notes"].(string)
	difficulty, _ := req.Params.Arguments["difficulty"].(string)

	categories, _ := req.Params.Arguments["categories"].([]interface{})
	rating, _ := req.Params.Arguments["rating"].(float64)

	cats := make([]string, len(categories))
	for i, c := range categories {
		cats[i], _ = c.(string)
	}

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.SaveRecipe(ctx, paprika.Recipe{
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
		Categories:  cats,
		Rating:      int(rating),
	})
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Created recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}

func getGroceryListTool() mcp.Tool {
	return mcp.NewTool("get_grocery_list",
		mcp.WithDescription("Fetch all items in a Paprika grocery list with their current aisle assignments."),
		mcp.WithString("list_name",
			mcp.Description("Name of the grocery list (not yet implemented — all items are returned regardless of this value)."),
		),
	)
}

func (s *Server) getGroceryList(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	items, err := s.paprika3.ListGroceryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var sb strings.Builder
	sb.WriteString("## Grocery List\n\n")
	sb.WriteString("| Item | UID | Aisle | Checked |\n|---|---|---|---|\n")
	for _, item := range items {
		name := item.Name
		if name == "" {
			name = item.Ingredient
		}
		checked := " "
		if item.Purchased {
			checked = "x"
		}
		sb.WriteString(fmt.Sprintf("| %s | %s | %s | [%s] |\n", name, item.UID, item.Aisle, checked))
	}

	return mcp.NewToolResultText(sb.String()), nil
}

func updateGroceryItemAisleTool() mcp.Tool {
	return mcp.NewTool("update_grocery_item_aisle",
		mcp.WithDescription("Set the aisle label on one or more grocery items. Pass an array of {uid, aisle} objects."),
		mcp.WithArray("items",
			mcp.Description("Array of objects with 'uid' (string) and 'aisle' (string) fields."),
			mcp.Required(),
		),
	)
}

func (s *Server) updateGroceryItemAisle(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	rawItems, ok := req.Params.Arguments["items"].([]interface{})
	if !ok {
		return mcp.NewToolResultError("items must be an array"), nil
	}

	existing, err := s.paprika3.ListGroceryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	byUID := make(map[string]paprika.GroceryItem, len(existing))
	for _, item := range existing {
		byUID[item.UID] = item
	}

	var updated, errs []string
	for _, raw := range rawItems {
		m, _ := raw.(map[string]interface{})
		uid, _ := m["uid"].(string)
		aisle, _ := m["aisle"].(string)
		if uid == "" || aisle == "" {
			errs = append(errs, fmt.Sprintf("skipped entry missing uid or aisle: %v", m))
			continue
		}
		item, exists := byUID[uid]
		if !exists {
			errs = append(errs, fmt.Sprintf("uid not found: %s", uid))
			continue
		}
		item.Aisle = aisle
		if err := s.paprika3.UpdateGroceryItem(ctx, item); err != nil {
			errs = append(errs, fmt.Sprintf("failed to update %s: %v", uid, err))
			continue
		}
		updated = append(updated, item.Ingredient)
	}

	msg := fmt.Sprintf("Updated %d items.", len(updated))
	if len(errs) > 0 {
		msg += "\nErrors:\n- " + strings.Join(errs, "\n- ")
	}
	return mcp.NewToolResultText(msg), nil
}

func addGroceryItemTool() mcp.Tool {
	return mcp.NewTool("add_grocery_item",
		mcp.WithDescription("Add a new item to the Paprika grocery list."),
		mcp.WithString("name", mcp.Description("Display name for the item"), mcp.Required()),
		mcp.WithString("ingredient", mcp.Description("Ingredient name (used for matching/grouping)"), mcp.Required()),
		mcp.WithString("quantity", mcp.Description("Quantity string, e.g. '2 lbs' or '1 can'"), mcp.DefaultString("")),
		mcp.WithString("aisle", mcp.Description("Aisle label"), mcp.DefaultString("")),
		mcp.WithString("recipe", mcp.Description("Recipe name this item is for"), mcp.DefaultString("")),
		mcp.WithString("recipe_uid", mcp.Description("UID of the recipe this item is for"), mcp.DefaultString("")),
	)
}

func (s *Server) addGroceryItem(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	name, _ := req.Params.Arguments["name"].(string)
	ingredient, _ := req.Params.Arguments["ingredient"].(string)
	quantity, _ := req.Params.Arguments["quantity"].(string)
	aisle, _ := req.Params.Arguments["aisle"].(string)
	recipe, _ := req.Params.Arguments["recipe"].(string)
	recipeUID, _ := req.Params.Arguments["recipe_uid"].(string)

	// Fetch existing items to copy list_uid and build aisle name → aisle_uid map.
	existing, err := s.paprika3.ListGroceryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("failed to fetch grocery list: %v", err)), nil
	}
	var listUID string
	aisleUIDs := make(map[string]string) // aisle name → aisle_uid
	for _, it := range existing {
		if listUID == "" {
			listUID = it.ListUID
		}
		if it.Aisle != "" && it.AisleUID != "" {
			aisleUIDs[it.Aisle] = it.AisleUID
		}
	}

	// Auto-assign aisle from map if caller didn't provide one.
	if aisle == "" {
		aisle, _ = s.aisleMap.Lookup(ingredient)
	}
	aisleUID := aisleUIDs[aisle]

	var recipePtr, recipeUIDPtr *string
	if recipe != "" {
		recipePtr = &recipe
	}
	if recipeUID != "" {
		recipeUIDPtr = &recipeUID
	}

	item := paprika.GroceryItem{
		Name:       name,
		Ingredient: ingredient,
		Quantity:   quantity,
		Aisle:      aisle,
		AisleUID:   aisleUID,
		Recipe:     recipePtr,
		RecipeUID:  recipeUIDPtr,
		ListUID:    listUID,
	}

	if err := s.paprika3.SaveGroceryItem(ctx, item); err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	return mcp.NewToolResultText(fmt.Sprintf("Added '%s' to grocery list.", name)), nil
}

// aisleCandidate represents a proposed aisle change for a single item.
type aisleCandidate struct {
	displayName  string
	currentAisle string
	newAisle     string
	apply        func(ctx context.Context) error
}

// applyAisleAssignments renders a table of proposed aisle changes and optionally commits them.
// unknownNote is appended below the unknown-items list if non-empty.
func (s *Server) applyAisleAssignments(
	ctx context.Context,
	toolName string,
	dryRun bool,
	proposals []aisleCandidate,
	unknown []string,
	unknownNote string,
) (*mcp.CallToolResult, error) {
	var sb strings.Builder
	mode := "DRY RUN — no changes written"
	if !dryRun {
		mode = "APPLYING CHANGES"
	}
	sb.WriteString(fmt.Sprintf("## %s (%s)\n\n", toolName, mode))

	if len(proposals) > 0 {
		sb.WriteString("### Changes\n\n| Item | Current Aisle | → New Aisle |\n|---|---|---|\n")
		var applyErrs []string
		for _, p := range proposals {
			sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", p.displayName, p.currentAisle, p.newAisle))
			if !dryRun {
				if err := p.apply(ctx); err != nil {
					applyErrs = append(applyErrs, fmt.Sprintf("%s: %v", p.displayName, err))
				}
			}
		}
		if len(applyErrs) > 0 {
			sb.WriteString("\n### Errors\n\n")
			for _, e := range applyErrs {
				sb.WriteString(fmt.Sprintf("- %s\n", e))
			}
		}
	} else {
		sb.WriteString("All items already have correct aisle assignments.\n")
	}

	if len(unknown) > 0 {
		sb.WriteString("\n### Unknown items (not in aisle map — review manually)\n\n")
		for _, u := range unknown {
			sb.WriteString(fmt.Sprintf("- %s\n", u))
		}
		if unknownNote != "" {
			sb.WriteString("\n" + unknownNote + "\n")
		}
	}

	return mcp.NewToolResultText(sb.String()), nil
}

func setupWoodmansAislesTool() mcp.Tool {
	return mcp.NewTool("setup_woodmans_aisles",
		mcp.WithDescription("Map all grocery list items to their Woodman's East aisle. dry_run=true (default) shows proposed changes without writing. Set dry_run=false to commit. Items not found in the aisle map are flagged for manual review."),
		mcp.WithBoolean("dry_run",
			mcp.Description("If true (default), return proposed changes without writing to Paprika."),
		),
	)
}

func (s *Server) setupWoodmansAisles(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	dryRun := true
	if v, ok := req.Params.Arguments["dry_run"].(bool); ok {
		dryRun = v
	}

	items, err := s.paprika3.ListGroceryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var proposals []aisleCandidate
	var unknown []string

	for _, item := range items {
		lookupKey := item.Name
		if lookupKey == "" {
			lookupKey = item.Ingredient
		}
		aisle, found := s.aisleMap.Lookup(lookupKey)
		if !found {
			unknown = append(unknown, lookupKey)
			continue
		}
		if aisle != item.Aisle {
			captured := item
			displayName := item.Name
			if displayName == "" {
				displayName = item.Ingredient
			}
			proposals = append(proposals, aisleCandidate{
				displayName:  displayName,
				currentAisle: item.Aisle,
				newAisle:     aisle,
				apply: func(ctx context.Context) error {
					captured.Aisle = aisle
					return s.paprika3.UpdateGroceryItem(ctx, captured)
				},
			})
		}
	}

	return s.applyAisleAssignments(ctx, "setup_woodmans_aisles", dryRun, proposals, unknown,
		"To add them: update `aisles/woodmans_east.json` and re-run.")
}

func setupPantryAislesTool() mcp.Tool {
	return mcp.NewTool("setup_pantry_aisles",
		mcp.WithDescription("Map all pantry items to their aisle using the aisle map. dry_run=true (default) shows proposed changes without writing. Set dry_run=false to commit. Items not found in the aisle map are flagged for manual review."),
		mcp.WithBoolean("dry_run",
			mcp.Description("If true (default), return proposed changes without writing to Paprika."),
		),
	)
}

func (s *Server) setupPantryAisles(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	dryRun := true
	if v, ok := req.Params.Arguments["dry_run"].(bool); ok {
		dryRun = v
	}

	items, err := s.paprika3.ListPantryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var proposals []aisleCandidate
	var unknown []string

	for _, item := range items {
		aisle, found := s.aisleMap.Lookup(item.Ingredient)
		if !found {
			unknown = append(unknown, item.Ingredient)
			continue
		}
		if aisle != item.Aisle {
			captured := item
			proposals = append(proposals, aisleCandidate{
				displayName:  item.Ingredient,
				currentAisle: item.Aisle,
				newAisle:     aisle,
				apply: func(ctx context.Context) error {
					captured.Aisle = aisle
					return s.paprika3.SavePantryItem(ctx, captured)
				},
			})
		}
	}

	return s.applyAisleAssignments(ctx, "setup_pantry_aisles", dryRun, proposals, unknown, "")
}

func (s *Server) updateRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	uid, ok := req.Params.Arguments["uid"].(string)
	if !ok || len(uid) == 0 {
		return nil, errors.New("uid is required")
	}
	name, ok := req.Params.Arguments["name"].(string)
	if !ok || len(name) == 0 {
		return nil, errors.New("name is required")
	}
	ingredients, ok := req.Params.Arguments["ingredients"].(string)
	if !ok || len(ingredients) == 0 {
		return nil, errors.New("ingredients are required")
	}
	directions, ok := req.Params.Arguments["directions"].(string)
	if !ok || len(directions) == 0 {
		return nil, errors.New("directions are required")
	}
	description, ok := req.Params.Arguments["description"].(string)
	if !ok {
		return nil, errors.New("description is required")
	}
	servings, ok := req.Params.Arguments["servings"].(string)
	if !ok {
		return nil, errors.New("servings is required")
	}
	prepTime, ok := req.Params.Arguments["prep_time"].(string)
	if !ok {
		return nil, errors.New("prepTime is required")
	}
	cookTime, ok := req.Params.Arguments["cook_time"].(string)
	if !ok {
		return nil, errors.New("cookTime is required")
	}
	notes, ok := req.Params.Arguments["notes"].(string)
	if !ok {
		return nil, errors.New("notes is required")
	}
	difficulty, ok := req.Params.Arguments["difficulty"].(string)
	if !ok {
		return nil, errors.New("difficulty is required")
	}

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	recipe := paprika.Recipe{
		UID:         uid,
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
	}

	if rawCats, ok := req.Params.Arguments["categories"]; ok && rawCats != nil {
		categories, _ := rawCats.([]interface{})
		cats := make([]string, len(categories))
		for i, c := range categories {
			cats[i], _ = c.(string)
		}
		recipe.Categories = cats
	}

	if rawRating, ok := req.Params.Arguments["rating"]; ok && rawRating != nil {
		rating, _ := rawRating.(float64)
		recipe.Rating = int(rating)
	}

	savedRecipe, err := s.paprika3.SaveRecipe(ctx, recipe)
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Updated recipe", "name", savedRecipe.Name, "uid", savedRecipe.UID, "duration", duration)

	return mcp.NewToolResultResource(savedRecipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", savedRecipe.UID),
		MIMEType: "text/markdown",
		Text:     savedRecipe.ToMarkdown(),
	}), nil
}

func getMealPlanTool() mcp.Tool {
	return mcp.NewTool("get_meal_plan",
		mcp.WithDescription("Fetch the meal plan for a date range."),
		mcp.WithString("start_date",
			mcp.Description("Start date in YYYY-MM-DD format."),
			mcp.Required(),
		),
		mcp.WithString("end_date",
			mcp.Description("End date in YYYY-MM-DD format."),
			mcp.Required(),
		),
	)
}

func (s *Server) getMealPlan(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	startStr, _ := req.Params.Arguments["start_date"].(string)
	endStr, _ := req.Params.Arguments["end_date"].(string)

	start, err := time.Parse("2006-01-02", startStr)
	if err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("invalid start_date: %v", err)), nil
	}
	end, err := time.Parse("2006-01-02", endStr)
	if err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("invalid end_date: %v", err)), nil
	}
	if end.Before(start) {
		return mcp.NewToolResultError("end_date must not be before start_date"), nil
	}

	entries, err := s.paprika3.ListMealPlanEntries(ctx, start, end)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	mealTypeName := map[int]string{0: "Breakfast", 1: "Lunch", 2: "Dinner", 3: "Snack"}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("## Meal Plan: %s to %s\n\n", startStr, endStr))
	if len(entries) == 0 {
		sb.WriteString("No meals planned for this period.\n")
	} else {
		sb.WriteString("| Date | Meal | Recipe |\n|---|---|---|\n")
		for _, e := range entries {
				displayDate := e.Date
			if len(displayDate) > 10 {
				displayDate = displayDate[:10]
			}
			sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", displayDate, mealTypeName[e.MealType], e.RecipeName))
		}
	}

	return mcp.NewToolResultText(sb.String()), nil
}

func addMealToPlanTool() mcp.Tool {
	return mcp.NewTool("add_meal_to_plan",
		mcp.WithDescription("Add a recipe to the meal plan. Idempotent — if the same recipe is already in this slot on this date, does nothing."),
		mcp.WithString("recipe_uid",
			mcp.Description("UID of the recipe to add."),
			mcp.Required(),
		),
		mcp.WithString("date",
			mcp.Description("Date in YYYY-MM-DD format."),
			mcp.Required(),
		),
		mcp.WithString("meal_type",
			mcp.Description("One of: breakfast, lunch, dinner, snack"),
			mcp.Required(),
		),
	)
}

func (s *Server) addMealToPlan(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	recipeUID, _ := req.Params.Arguments["recipe_uid"].(string)
	if recipeUID == "" {
		return mcp.NewToolResultError("recipe_uid is required"), nil
	}
	dateStr, _ := req.Params.Arguments["date"].(string)
	mealTypeStr, _ := req.Params.Arguments["meal_type"].(string)

	mealTypeMap := map[string]int{
		"breakfast": paprika.MealTypeBreakfast,
		"lunch":     paprika.MealTypeLunch,
		"dinner":    paprika.MealTypeDinner,
		"snack":     paprika.MealTypeSnack,
	}
	mealType, ok := mealTypeMap[strings.ToLower(mealTypeStr)]
	if !ok {
		return mcp.NewToolResultError("meal_type must be one of: breakfast, lunch, dinner, snack"), nil
	}

	date, err := time.Parse("2006-01-02", dateStr)
	if err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("invalid date: %v", err)), nil
	}

	// Idempotency check.
	// time.Parse("2006-01-02", ...) returns UTC midnight. ListMealPlanEntries
	// filters using Truncate(24h) comparisons, also in UTC. This is correct
	// as long as the server is not running in a non-UTC timezone that shifts
	// the date boundary — keep TZ=UTC in the MCP config env to be safe.
	existing, err := s.paprika3.ListMealPlanEntries(ctx, date, date)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	for _, e := range existing {
		if e.RecipeUID == recipeUID && e.MealType == mealType {
			return mcp.NewToolResultText(fmt.Sprintf(
				"Recipe already in %s slot on %s — no change made.", mealTypeStr, dateStr,
			)), nil
		}
	}

	entry := paprika.MealPlanEntry{
		RecipeUID:  recipeUID,
		RecipeName: recipeUID, // fallback: use UID as name; Paprika will resolve the display name
		Date:       dateStr + " 00:00:00", // Paprika requires "YYYY-MM-DD 00:00:00" format
		MealType:   mealType,
	}

	if err := s.paprika3.SaveMealPlanEntry(ctx, entry); err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	return mcp.NewToolResultText(fmt.Sprintf(
		"Added recipe to %s on %s.", mealTypeStr, dateStr,
	)), nil
}

func removeMealFromPlanTool() mcp.Tool {
	return mcp.NewTool("remove_meal_from_plan",
		mcp.WithDescription("Remove a meal from the plan by its UID. Use get_meal_plan to find the entry UID."),
		mcp.WithString("uid",
			mcp.Description("UID of the meal plan entry to remove."),
			mcp.Required(),
		),
	)
}

func (s *Server) removeMealFromPlan(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	uid, _ := req.Params.Arguments["uid"].(string)
	if uid == "" {
		return mcp.NewToolResultError("uid is required"), nil
	}

	// Look up the entry across a wide window so we can confirm it exists
	// and get its full fields (date, type, recipe_uid) for the soft-delete payload.
	start := time.Now().AddDate(0, -1, 0)
	end := time.Now().AddDate(0, 1, 0)
	entries, err := s.paprika3.ListMealPlanEntries(ctx, start, end)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var target *paprika.MealPlanEntry
	for i := range entries {
		if entries[i].UID == uid {
			target = &entries[i]
			break
		}
	}
	if target == nil {
		return mcp.NewToolResultError(fmt.Sprintf("meal plan entry %s not found", uid)), nil
	}

	if err := s.paprika3.DeleteMealPlanEntry(ctx, *target); err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	return mcp.NewToolResultText(fmt.Sprintf("Removed %q from meal plan.", target.RecipeName)), nil
}

func listRecipesTool() mcp.Tool {
	return mcp.NewTool("list_recipes",
		mcp.WithDescription("List all recipes with name, UID, categories, prep/cook time, star rating, and last prepared date. Use get_recipe to fetch full ingredients and directions for a specific recipe."),
	)
}

func (s *Server) listRecipes(ctx context.Context, _ mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	s.recipesMu.RLock()
	recipes := make([]*paprika.Recipe, 0, len(s.recipes))
	for _, r := range s.recipes {
		recipes = append(recipes, r)
	}
	s.recipesMu.RUnlock()

	if len(recipes) == 0 {
		return mcp.NewToolResultText("No recipes found. Resources may still be loading — try again in a moment."), nil
	}

	lastPrepared, err := s.paprika3.GetLastPreparedDates(ctx)
	if err != nil {
		s.logger.Warn("failed to fetch last prepared dates", "error", err)
		lastPrepared = map[string]time.Time{}
	}

	sort.Slice(recipes, func(i, j int) bool {
		return recipes[i].Name < recipes[j].Name
	})

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("## Recipes (%d total)\n\n", len(recipes)))
	sb.WriteString("| Name | UID | Categories | Prep | Cook | Rating | Last Prepared |\n|---|---|---|---|---|---|---|\n")
	for _, r := range recipes {
		cats := strings.Join(r.Categories, ", ")
		lp := ""
		if t, ok := lastPrepared[r.UID]; ok {
			lp = t.Format("2006-01-02")
		}
		sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %d | %s |\n",
			r.Name, r.UID, cats, r.PrepTime, r.CookTime, r.Rating, lp))
	}
	return mcp.NewToolResultText(sb.String()), nil
}

func getRecipeTool() mcp.Tool {
	return mcp.NewTool("get_recipe",
		mcp.WithDescription("Fetch full recipe content (ingredients, directions, notes) by UID."),
		mcp.WithString("uid", mcp.Description("The UID of the recipe."), mcp.Required()),
	)
}

func (s *Server) getRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	uid, _ := req.Params.Arguments["uid"].(string)
	if uid == "" {
		return mcp.NewToolResultError("uid is required"), nil
	}

	s.recipesMu.RLock()
	recipe, ok := s.recipes[uid]
	s.recipesMu.RUnlock()

	if !ok {
		ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
		defer cancel()
		var err error
		recipe, err = s.paprika3.GetRecipe(ctx, uid)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
	}

	lastPrepared, err := s.paprika3.GetLastPreparedDates(ctx)
	if err != nil {
		s.logger.Warn("failed to fetch last prepared dates", "error", err)
		lastPrepared = map[string]time.Time{}
	}

	var lp string
	if t, ok := lastPrepared[recipe.UID]; ok {
		lp = t.Format("2006-01-02")
	}

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdownWithLastPrepared(lp),
	}), nil
}

func getPantryTool() mcp.Tool {
	return mcp.NewTool("get_pantry",
		mcp.WithDescription("Fetch all items in the Paprika pantry with name, quantity, and in-stock status."),
	)
}

func (s *Server) getPantry(ctx context.Context, _ mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	items, err := s.paprika3.ListPantryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	if len(items) == 0 {
		return mcp.NewToolResultText("Pantry is empty."), nil
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("## Pantry (%d items)\n\n", len(items)))
	sb.WriteString("| Item | Quantity | In Stock |\n|---|---|---|\n")
	for _, item := range items {
		inStock := "no"
		if item.InStock {
			inStock = "yes"
		}
		sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", item.Ingredient, item.Quantity, inStock))
	}
	return mcp.NewToolResultText(sb.String()), nil
}

func addPantryItemTool() mcp.Tool {
	return mcp.NewTool("add_pantry_item",
		mcp.WithDescription("Add a new item to the Paprika pantry."),
		mcp.WithString("ingredient", mcp.Description("Name of the ingredient."), mcp.Required()),
		mcp.WithString("quantity", mcp.Description("Quantity string, e.g. '2 lbs', '1 dozen'."), mcp.Required()),
		mcp.WithBoolean("in_stock", mcp.Description("Whether the item is currently in stock. Defaults to true.")),
	)
}

func (s *Server) addPantryItem(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	ingredient, _ := req.Params.Arguments["ingredient"].(string)
	if ingredient == "" {
		return mcp.NewToolResultError("ingredient is required"), nil
	}
	quantity, _ := req.Params.Arguments["quantity"].(string)
	if quantity == "" {
		return mcp.NewToolResultError("quantity is required"), nil
	}
	inStock := true
	if v, ok := req.Params.Arguments["in_stock"].(bool); ok {
		inStock = v
	}

	aisle, _ := s.aisleMap.Lookup(ingredient)

	item := paprika.PantryItem{
		Ingredient: ingredient,
		Quantity:   quantity,
		InStock:    inStock,
		Aisle:      aisle,
	}
	if err := s.paprika3.SavePantryItem(ctx, item); err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(fmt.Sprintf("Added %s (%s) to pantry.", ingredient, quantity)), nil
}

func updatePantryItemTool() mcp.Tool {
	return mcp.NewTool("update_pantry_item",
		mcp.WithDescription("Update an existing pantry item's quantity or in-stock status. Use get_pantry to find the item's name first."),
		mcp.WithString("ingredient", mcp.Description("Ingredient name exactly as shown in get_pantry."), mcp.Required()),
		mcp.WithString("quantity", mcp.Description("New quantity string, e.g. '5 lbs'.")),
		mcp.WithBoolean("in_stock", mcp.Description("Whether the item is currently in stock.")),
	)
}

func (s *Server) updatePantryItem(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	ingredient, _ := req.Params.Arguments["ingredient"].(string)
	if ingredient == "" {
		return mcp.NewToolResultError("ingredient is required"), nil
	}

	items, err := s.paprika3.ListPantryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var target *paprika.PantryItem
	for i := range items {
		if strings.EqualFold(items[i].Ingredient, ingredient) {
			target = &items[i]
			break
		}
	}
	if target == nil {
		return mcp.NewToolResultError(fmt.Sprintf("no pantry item found with ingredient %q", ingredient)), nil
	}

	if q, ok := req.Params.Arguments["quantity"].(string); ok && q != "" {
		target.Quantity = q
	}
	if v, ok := req.Params.Arguments["in_stock"].(bool); ok {
		target.InStock = v
	}

	if err := s.paprika3.SavePantryItem(ctx, *target); err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	inStock := "in stock"
	if !target.InStock {
		inStock = "out of stock"
	}
	return mcp.NewToolResultText(fmt.Sprintf("Updated %s: %s, %s.", target.Ingredient, target.Quantity, inStock)), nil
}

func deletePantryItemTool() mcp.Tool {
	return mcp.NewTool("delete_pantry_item",
		mcp.WithDescription("Permanently remove a pantry item by ingredient name. Use during close-cycle pantry hygiene to remove items you no longer buy."),
		mcp.WithString("ingredient",
			mcp.Description("Ingredient name exactly as shown in get_pantry."),
			mcp.Required(),
		),
	)
}

func (s *Server) deletePantryItem(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	ingredient, _ := req.Params.Arguments["ingredient"].(string)
	if ingredient == "" {
		return mcp.NewToolResultError("ingredient is required"), nil
	}

	items, err := s.paprika3.ListPantryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var target *paprika.PantryItem
	for i := range items {
		if strings.EqualFold(items[i].Ingredient, ingredient) {
			target = &items[i]
			break
		}
	}
	if target == nil {
		return mcp.NewToolResultError(fmt.Sprintf("no pantry item found with ingredient %q", ingredient)), nil
	}

	if err := s.paprika3.DeletePantryItem(ctx, *target); err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	return mcp.NewToolResultText(fmt.Sprintf("Deleted %s from pantry.", target.Ingredient)), nil
}

func uncheckGroceryItemsTool() mcp.Tool {
	return mcp.NewTool("uncheck_grocery_items",
		mcp.WithDescription("Set purchased=false on one or more grocery items by UID, keeping them on the grocery list for the next shopping trip. Use for staple items that should remain on the list after syncing to the pantry."),
		mcp.WithArray("uids",
			mcp.Description("Array of grocery item UIDs to uncheck."),
			mcp.Required(),
		),
	)
}

func (s *Server) uncheckGroceryItems(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	rawUIDs, ok := req.Params.Arguments["uids"].([]interface{})
	if !ok {
		if s, ok2 := req.Params.Arguments["uids"].(string); ok2 {
			if err := json.Unmarshal([]byte(s), &rawUIDs); err != nil {
				return mcp.NewToolResultError("uids must be an array"), nil
			}
		} else {
			return mcp.NewToolResultError("uids must be an array"), nil
		}
	}

	existing, err := s.paprika3.ListGroceryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	byUID := make(map[string]paprika.GroceryItem, len(existing))
	for _, item := range existing {
		byUID[item.UID] = item
	}

	var unchecked, errs []string
	for _, raw := range rawUIDs {
		uid, _ := raw.(string)
		if uid == "" {
			errs = append(errs, "skipped empty UID")
			continue
		}
		item, exists := byUID[uid]
		if !exists {
			errs = append(errs, fmt.Sprintf("uid not found: %s", uid))
			continue
		}
		item.Purchased = false
		if err := s.paprika3.UpdateGroceryItem(ctx, item); err != nil {
			errs = append(errs, fmt.Sprintf("failed to uncheck %s: %v", item.Ingredient, err))
			continue
		}
		unchecked = append(unchecked, item.Ingredient)
	}

	msg := fmt.Sprintf("Unchecked %d item(s).", len(unchecked))
	if len(errs) > 0 {
		msg += "\nErrors:\n- " + strings.Join(errs, "\n- ")
	}
	return mcp.NewToolResultText(msg), nil
}

func deleteGroceryItemsTool() mcp.Tool {
	return mcp.NewTool("delete_grocery_items",
		mcp.WithDescription("Remove one or more grocery items from the list by UID. Use for non-staple items after syncing them to the pantry."),
		mcp.WithArray("uids",
			mcp.Description("Array of grocery item UIDs to delete."),
			mcp.Required(),
		),
	)
}

func (s *Server) deleteGroceryItems(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	rawUIDs, ok := req.Params.Arguments["uids"].([]interface{})
	if !ok {
		if s, ok2 := req.Params.Arguments["uids"].(string); ok2 {
			if err := json.Unmarshal([]byte(s), &rawUIDs); err != nil {
				return mcp.NewToolResultError("uids must be an array"), nil
			}
		} else {
			return mcp.NewToolResultError("uids must be an array"), nil
		}
	}

	existing, err := s.paprika3.ListGroceryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	byUID := make(map[string]paprika.GroceryItem, len(existing))
	for _, item := range existing {
		byUID[item.UID] = item
	}

	var deleted, errs []string
	for _, raw := range rawUIDs {
		uid, _ := raw.(string)
		if uid == "" {
			errs = append(errs, "skipped empty UID")
			continue
		}
		item, exists := byUID[uid]
		if !exists {
			errs = append(errs, fmt.Sprintf("uid not found: %s", uid))
			continue
		}
		if err := s.paprika3.DeleteGroceryItem(ctx, item); err != nil {
			errs = append(errs, fmt.Sprintf("failed to delete %s: %v", item.Ingredient, err))
			continue
		}
		deleted = append(deleted, item.Ingredient)
	}

	msg := fmt.Sprintf("Deleted %d item(s).", len(deleted))
	if len(errs) > 0 {
		msg += "\nErrors:\n- " + strings.Join(errs, "\n- ")
	}
	return mcp.NewToolResultText(msg), nil
}

func syncGroceryListToPantryTool() mcp.Tool {
	return mcp.NewTool("sync_grocery_list_to_pantry",
		mcp.WithDescription("DEPRECATED: use the sync-grocery-list skill instead, which handles staple items correctly. Legacy: move all checked grocery items into the pantry and remove them from the grocery list."),
	)
}

func (s *Server) syncGroceryListToPantry(ctx context.Context, _ mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	groceries, err := s.paprika3.ListGroceryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var purchased []paprika.GroceryItem
	for _, item := range groceries {
		if item.Purchased {
			purchased = append(purchased, item)
		}
	}

	if len(purchased) == 0 {
		return mcp.NewToolResultText("No checked items on the grocery list."), nil
	}

	pantry, err := s.paprika3.ListPantryItems(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	pantryByName := make(map[string]paprika.PantryItem, len(pantry))
	for _, p := range pantry {
		pantryByName[strings.ToLower(p.Ingredient)] = p
	}

	var added, updated, failed []string
	for _, item := range purchased {
		ingredient := item.Ingredient
		if ingredient == "" {
			ingredient = item.Name
		}

		existing, exists := pantryByName[strings.ToLower(ingredient)]
		if exists {
			existing.InStock = true
			if item.Quantity != "" {
				existing.Quantity = item.Quantity
			}
			if err := s.paprika3.SavePantryItem(ctx, existing); err != nil {
				failed = append(failed, fmt.Sprintf("%s (update pantry): %v", ingredient, err))
				continue
			}
			updated = append(updated, ingredient)
		} else {
			aisle, _ := s.aisleMap.Lookup(ingredient)
			newItem := paprika.PantryItem{
				Ingredient: ingredient,
				Quantity:   item.Quantity,
				InStock:    true,
				Aisle:      aisle,
			}
			if err := s.paprika3.SavePantryItem(ctx, newItem); err != nil {
				failed = append(failed, fmt.Sprintf("%s (add to pantry): %v", ingredient, err))
				continue
			}
			added = append(added, ingredient)
		}

		if err := s.paprika3.DeleteGroceryItem(ctx, item); err != nil {
			failed = append(failed, fmt.Sprintf("%s (remove from grocery list): %v", ingredient, err))
		}
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("## sync_grocery_list_to_pantry\n\nProcessed %d checked item(s).\n\n", len(purchased)))
	if len(added) > 0 {
		sb.WriteString(fmt.Sprintf("**Added to pantry (%d):**\n", len(added)))
		for _, a := range added {
			sb.WriteString(fmt.Sprintf("- %s\n", a))
		}
		sb.WriteString("\n")
	}
	if len(updated) > 0 {
		sb.WriteString(fmt.Sprintf("**Updated in pantry (%d):**\n", len(updated)))
		for _, u := range updated {
			sb.WriteString(fmt.Sprintf("- %s\n", u))
		}
		sb.WriteString("\n")
	}
	if len(failed) > 0 {
		sb.WriteString(fmt.Sprintf("**Errors (%d):**\n", len(failed)))
		for _, f := range failed {
			sb.WriteString(fmt.Sprintf("- %s\n", f))
		}
	}
	return mcp.NewToolResultText(sb.String()), nil
}

func getHouseholdRulesTool() mcp.Tool {
	return mcp.NewTool("get_household_rules",
		mcp.WithDescription("Return all household cooking and shopping rules. Rules govern substitutions (e.g. venison→ground beef) and quantity adjustments (e.g. double all proteins). Always read these before generating a grocery list or planning meals."),
	)
}

func (s *Server) getHouseholdRules(_ context.Context, _ mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	s.rulesMu.RLock()
	defer s.rulesMu.RUnlock()
	return mcp.NewToolResultText(s.householdRules.ToMarkdown()), nil
}

func setHouseholdRuleTool() mcp.Tool {
	return mcp.NewTool("set_household_rule",
		mcp.WithDescription("Add or update a household rule. Rules are persisted to disk and available in future sessions. Existing rules with the same id are replaced."),
		mcp.WithString("id", mcp.Description("Unique identifier for the rule (e.g. 'substitute-venison', 'double-proteins')."), mcp.Required()),
		mcp.WithString("type", mcp.Description("Rule type (e.g. 'substitution', 'quantity_multiplier', 'note')."), mcp.Required()),
		mcp.WithString("description", mcp.Description("Human-readable description of what the rule does."), mcp.Required()),
		mcp.WithString("params", mcp.Description("Optional JSON object of rule parameters (e.g. '{\"from\":\"venison\",\"to\":\"ground beef\"}')."), mcp.DefaultString("")),
	)
}

func (s *Server) setHouseholdRule(_ context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	id, _ := req.Params.Arguments["id"].(string)
	ruleType, _ := req.Params.Arguments["type"].(string)
	description, _ := req.Params.Arguments["description"].(string)
	paramsStr, _ := req.Params.Arguments["params"].(string)

	if id == "" || ruleType == "" || description == "" {
		return mcp.NewToolResultError("id, type, and description are required"), nil
	}

	rule := rules.Rule{
		ID:          id,
		Type:        ruleType,
		Description: description,
	}

	if paramsStr != "" {
		var params map[string]any
		if err := json.Unmarshal([]byte(paramsStr), &params); err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("invalid params JSON: %v", err)), nil
		}
		rule.Params = params
	}

	s.rulesMu.Lock()
	s.householdRules = s.householdRules.Upsert(rule)
	snapshot := s.householdRules
	path := s.householdRulesPath
	s.rulesMu.Unlock()

	if err := snapshot.Save(path); err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("rule updated in memory but failed to save to disk: %v", err)), nil
	}

	return mcp.NewToolResultText(fmt.Sprintf("Rule '%s' saved.", id)), nil
}
